In [1]:
import numpy as np

In [ ]:
# Basic array creation

print(type(np.arange(15)))
print(np.arange(15))

<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
# Reshape and inspect properties

a = np.arange(15).reshape(3, 5)
print(a)
b = np.arange(15).reshape(-1, 5) # -1 is a placeholder and numpy automatically calculates the number of rows
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
# Basic Properties

print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)
print(a.size)

(3, 5)
2
int64
8
15


In [ ]:
# Creating arrays from lists

b = np.array([1, 2, 3])
print(b)
print(type(b))
c = np.array([(1.5, 2, 3), (4, 5, 6), [7, 8, 9]])
print(c)
print(type(c))

[1 2 3]
<class 'numpy.ndarray'>
[[1.5 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]
<class 'numpy.ndarray'>


In [ ]:
# Special arrays

d = np.ones([2, 3, 4], dtype=np.int16)
print(d)
print(type(d))                            
print(d[0])
print(type(d[0]))                        
print(d[0][0])                            
print(d[0, 0])                            
print(type(d[0][0])) 
print(d[0][0][0])
print(d[0, 0, 0])
print(type(d[0][0][0]))                    

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
<class 'numpy.ndarray'>
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
<class 'numpy.ndarray'>
[1 1 1 1]
[1 1 1 1]
<class 'numpy.ndarray'>
1
1
<class 'numpy.int16'>


In [ ]:
# Simple space jumps vs linespace

e = np.arange(0, 2, 0.3)
print(e)                                

# linspace example Creates n evenly spaced points from a to b
f = np.linspace(0, 2, 9)
print(f)                                

# Making 100 steps in randians between 0 and 2π
g = np.linspace(0, 2 * np.pi, 100)  
print(g[:5])                              
print(np.sin(g)[:5])                      

[0.  0.3 0.6 0.9 1.2 1.5 1.8]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[0.         0.06346652 0.12693304 0.19039955 0.25386607]
[0.         0.06342392 0.12659245 0.18925124 0.25114799]


In [ ]:
# Array arithmetic & matrix products

h = np.array([[1,2],[3,4]])
i = np.array([[5,6],[7,8]])
print(h * i) # simple product element wise
print(h @ i) # matrix multiplication
print(h.dot(i)) # dot product

j = np.ones((2,3), dtype="int64").reshape(3,2)
print(j)
print(j.dtype)                           # int64

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[1 1]
 [1 1]
 [1 1]]
int64


In [64]:
# Random number generation yield same values for seed 1

# Both same as seed starts from beginning
print(np.random.default_rng(1).random((2,3))) 
print(np.random.default_rng(1).random((2,3)))

# Both different as seed moves on
rg = np.random.default_rng(2)
print(rg.random((3,2)))
print(rg.random((3,2)))

# Random integers from 0 - 10
print(rg.integers(0, 10, (3, 4)))


[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]
[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]
[[0.26161213 0.29849114]
 [0.81422574 0.09191594]
 [0.60010053 0.72856053]]
[[0.18790107 0.05514663]
 [0.27496937 0.65743301]
 [0.56226566 0.15006226]]
[[7 4 6 6]
 [9 4 2 6]
 [9 9 8 6]]


In [18]:
# Addition of Float and int dtypes

k = np.ones((2,3), dtype=int)
print(k)
k *= 3
print(k)

l = rg.random((2,3))
print(l)
l += k
print(l)

# k+=l # error cannot store floating point values in int matrix k

[[1 1 1]
 [1 1 1]]
[[3 3 3]
 [3 3 3]]
[[0.51657819 0.59344352 0.86211798]
 [0.43818617 0.89224011 0.61371694]]
[[3.51657819 3.59344352 3.86211798]
 [3.43818617 3.89224011 3.61371694]]


In [19]:
# Exponential & grid generation

x = np.linspace(0, 5, 10) # x is an array of equidistant 10 points from 0 to 5 
y = np.exp(x) # y is an array in which each element is y[i] = e^x[i] or y = e^x for each point in x there is a corresponding point in exp(x) or e^x
print(x)
print(y)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[  1.           1.742909     3.03773178   5.29449005   9.22781435
  16.08324067  28.03162489  48.85657127  85.15255772 148.4131591 ]


In [2]:
# Peek to Peek Calculation

# Example 1: No axis specified (flattened array)
arr = np.array([1, 3, 5, 7, 9])
result = np.ptp(arr)
print(result)  # Output: 8 (9 - 1)

# Example 2: With a 2D array and axis specified
arr_2d = np.array([[1, 3, 5], [2, 4, 6]])
result_axis_0 = np.ptp(arr_2d, axis=0)
result_axis_1 = np.ptp(arr_2d, axis=1)
print(result_axis_0)  # Output: [1 1 1] (peak-to-peak across columns)
print(result_axis_1)  # Output: [4 4] (peak-to-peak across rows)

8
[1 1 1]
[4 4]


## Concatenation Of arrays 

In [32]:
# Concatenation is used for same dimensions

grid = np.arange(0, 18).reshape(3, 6)
print("Grid:\n", grid)

print("Concatenating both grids along axis = 0 (first axis):\n", np.concatenate([grid, grid], axis=0))
print("Concatenating both grids along axis = 1 (second axis):\n", np.concatenate([grid, grid], axis=1))

x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([7,8,9])
print("Concatenating x, y, z arrays:\n", np.concatenate([x,y,z]))

## Error as dimensions must be same
# print("Concatenating x and grid:\n", np.concatenate([x, grid]))

# For differnet dimensions we have to use np.vstack and np.hstack functions

## Vertical stack: Putting arrays on top of each other, Adds rows, same number of columns
print("np.vstack((x, y, z)):\n",np.vstack((x, y, z)))

a = np.array([1,2,3,4,5,6])
print("np.vstack([a, grid]):\n", np.vstack([a, grid]))

# Error as : the array at index 0 has size 3 (columns) and the array at index 1 has size 6 (columns)
# print(np.vstack([x, grid])) 

## Horizontal stack: Placing arrays side-by-side, Adds columns, same number of rows
print("np.hstack((x,y,z)):\n", np.hstack((x, y, z)))

# Error as : the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)
# print(np.hstack([x, grid])) 


Grid:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
Concatenating both grids along axis = 0 (first axis):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
Concatenating both grids along axis = 1 (second axis):
 [[ 0  1  2  3  4  5  0  1  2  3  4  5]
 [ 6  7  8  9 10 11  6  7  8  9 10 11]
 [12 13 14 15 16 17 12 13 14 15 16 17]]
Concatenating x, y, z arrays:
 [1 2 3 4 5 6 7 8 9]
np.vstack((x, y, z)):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
np.vstack([a, grid]):
 [[ 1  2  3  4  5  6]
 [ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
np.hstack((x,y,z)):
 [1 2 3 4 5 6 7 8 9]


In [ ]:
# ============================================================
#                         np.mgrid
# ============================================================

x = np.mgrid[0:5:1]
print(x) 

xg, yg = np.mgrid[0:5, 0:6]
print(xg)
print(yg)

print([(vx, vy) for rx, ry in zip(xg, yg) for vx, vy in zip(rx, ry)])
"""
mgrid gives as two 2D arrays as :
    x[i][j] is the row coordinate at position (i, j)
    y[i][j] is the column coordinate at position (i, j)
So (x[i][j], y[i][j]) gives you the full coordinate at position [i][j]

Grid points:

(0,0) (0,1) (0,2) (0,3) (0,4) (0,5)
(1,0) (1,1) (1,2) (1,3) (1,4) (1,5)
(2,0) (2,1) (2,2) (2,3) (2,4) (2,5)
(3,0) (3,1) (3,2) (3,3) (3,4) (3,5)
(4,0) (4,1) (4,2) (4,3) (4,4) (4,5)

These pairs are formed from x, y. """

x, y = np.mgrid[0:1:5j, 0:1:5j]
print(x)
print(y)

[0 1 2 3 4]
[[0 0 0 0 0 0]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [3 3 3 3 3 3]
 [4 4 4 4 4 4]]
[[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]
[(np.int64(0), np.int64(0)), (np.int64(0), np.int64(1)), (np.int64(0), np.int64(2)), (np.int64(0), np.int64(3)), (np.int64(0), np.int64(4)), (np.int64(0), np.int64(5)), (np.int64(1), np.int64(0)), (np.int64(1), np.int64(1)), (np.int64(1), np.int64(2)), (np.int64(1), np.int64(3)), (np.int64(1), np.int64(4)), (np.int64(1), np.int64(5)), (np.int64(2), np.int64(0)), (np.int64(2), np.int64(1)), (np.int64(2), np.int64(2)), (np.int64(2), np.int64(3)), (np.int64(2), np.int64(4)), (np.int64(2), np.int64(5)), (np.int64(3), np.int64(0)), (np.int64(3), np.int64(1)), (np.int64(3), np.int64(2)), (np.int64(3), np.int64(3)), (np.int64(3), np.int64(4)), (np.int64(3), np.int64(5)), (np.int64(4), np.int64(0)), (np.int64(4), np.int64(1)), (np.int64(4), np.int64(2)), (np.int64(4), np.int64(3)), (np.int64(4), np.int64(4)), (np.int64(4), np.int64(


# Summation ALONG AXES

In [ ]:
# ------------------------------
#         1D RANGE (1 axis)
# ------------------------------

# axis = 0 (along columns)
# give element as result
a = np.array([1,2,3,4])
print(a.sum())                           # 10
print(a.shape)                           # (4,)
print(a.sum(axis=0))                     # it collapses the axis 0 as this has single axis of 4 columns we merge all columns into a single scalar value

10
(4,)
10


In [ ]:
# ------------------------------
#         2D RANGE (2 axis)
# ------------------------------

# axis = 0 (along the rows), axis = 1 (alogn the column)
# gives 1D array as result
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a.sum())                           # 36
print(a.shape)                           # (2,4)
print(a.sum(axis=0))                     # it collapses the axis 0 (which are 2 rows, which means that we have to merge 2 rows) as we are performing sum we add those 2 rows converting them into 1D row with 4 columns
print(a.sum(axis=1))                     # it collapses the axis 1 (which is 4 columns, which means that we have to merge 4 columns) as we are performing sum we add those 4 columns converting each of them into individual element of 1D result row (each represeting sum of each row)

36
(2, 4)
[ 6  8 10 12]
[10 26]


In [ ]:
# ------------------------------
#         3D RANGE (3 axes)
# ------------------------------

# axis = 0 (along the 2D array), axis = 1 (alogn the row), axis = 2 (along the column)
# gives 2D array as result
a  = np.array([
            [ [1,2,3,4], 
              [5,6,7,8],
              [9,10,11,12]],

            [ [13,14,15,16],
              [17,18,19,20],
              [21,22,23,24]]
            ])
print(a.sum())                           # 300
print(a.shape)                           # (2,3,4)
print(a.sum(axis=0))                     # collapse axis = 0 (which is 2, means we have to merge the 2D arrays together such that after collapsing we should get 1 2D array with axis (3,4)) as we are performing sum of 2d arrays we got resultant 2D sum array with (3,4) shape one axis collapsed. a[0] + a[1]
print(a.sum(axis=1))                     # collapse axis = 1 (which is 3, means we have to merge the rows together such that after collapsing rows we should get (2,4)) as we are performing sum of rows we got resultant 2D sum array with (2,4) shape one axis collapsed. same as summing rows of each 2d array into one row. [a[0][0] + a[0][1] + a[0][2]] +  [a[1][0] + a[1][1] + a[1][2]]
print(a.sum(axis=2))                     # collapse axis = 2 (which is 4, means we have to merge the columns together such that after collaping columns we should get (2,3)) as we are performing sum of columns we got resultant 2D sum array with (2,3) shape one axis collapsed. same as suming columns of each row of 2D array to one scalar and appending in each row of 2d array. 

300
(2, 3, 4)
[[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]
[[15 18 21 24]
 [51 54 57 60]]
[[10 26 42]
 [58 74 90]]


# SLICING & SLICING ASSIGNMENT

In [30]:
# ------------------------------
#         1D RANGE (1 axis)
# ------------------------------

arr = np.arange(10)**3
print(arr)

arr[:6:2] = 1000            
print(arr)

[  0   1   8  27  64 125 216 343 512 729]
[1000    1 1000   27 1000  125  216  343  512  729]


In [10]:
# ------------------------------
#         2D RANGE (2 axes)
# ------------------------------
# syntax:   array[RowStartIncluded: RowEndExcluded: RowStep, ColumnStartIncluded : ColumnEndExcluded : ColumnStep]
#        or array[RowStartIncluded: RowEndExcluded: RowStep][ColumnStartIncluded : ColumnEndExcluded : ColumnStep]

m = np.arange(12).reshape(3,4)
print(f"m\n", m)
print(f"m[:2]\n", m[:2])
print(f"m[2:5]\n", m[2:5])

b = np.array(
      [[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])
print(f"b[2,3]\n", b[2,3])                              # 23
print(f"b[-2,-3]\n", b[-2, -3])                         # 31
print(f"b[0:5,1]\n", b[0:5, 1])                         # in 0,1,2,3,4 rows take only 1st column elements 
print(f"b[:,1]\n", b[:, 1])                             # in all rows take only 1st column elements 
print(f"b[2:5,1]\n", b[2:5, 1])                         # in 2,3,4 rows take only 1st column elements 
print(f"b[2:5,:]\n", b[2:5, :])                         # in 2,3,4 rows take all column elements 
print(f"b[:,::2]\n", b[:, ::2])                         # in all rows take only columns that are factor of 2 and 0 (0 is not a factor of 2) in this case index = 0 and 2 columns


# assume that python converts every -ve index to +ve and the apply steps
print(f"b[-1]\n", b[-1])                                # b[-1] == b[4]; take last row
print(f"b[-1,-1]\n", b[-1, -1])                         # b[-1, -1] == b[4, 3]; 43, last row last element
print(f"b[-2:]\n", b[-2:])                              # b[-2:] == b[-2::1] == b[3::1], so it start at index 3 or -2 and moves forward with 1 inc until reached end; take last 2 items at index = -2, -1
print(f"b[-2:0]\n", b[-2:0])                            # b[-2:0] == b[-2:0:1] == b[3:0:1] which is not possible we cannot go from index 3 or -2 to index 0 with jump of inc 1 (forward)
print(f"b[-2:0:-1]\n", b[-2:0:-1])                      # b[-2:0:-1] == b[3:0:-1] which is possible start at 3 and then take one step backwards dec 1. So first row is -2 or 3, second row will be -3 or 2, third row will be -4 or 1, forth row -5 or 0 is not included
print(f"b[-1::-1]\n", b[-1::-1])                        # b[-1::-1] == b[4::-1] which means that start at index/ row = 4 then append this row into a list and then move backward at index = 3 and continue appending; this effectively appends each row in reverse order in the same 2D martix
print(f"b[-1::-1,-1::-1]\n", b[-1::-1, -1::-1])         # b[-1::-1, -1::-1] == b[4::-1, 4::-1] which means pick rows in this order 4,3,2,1,0 and append them to the end of a np.array but before appending in reverse order you have to apply this order on their columns 4::-1 such that for each row take their columns in order 4,3,2,1,0 and append them to a 1D list. So that a reverse order of rows and columns is made
print(f"b[-1:-3:-1, -1:-3:-1]\n", b[-1:-3:-1, -1:-3:-1])  # b[-1:-3:-1, -1:-3:-1] lets understand in case of -ve indexes. Start at row (-1 == 4) and then move to row (-3 == 2) which is not included. First row we got is row (-1 or 4). Now we have to append this row to result but before that we have to apply the selection on columns elements "-1:-3:-1" which says take the last element of the column and then append that to the row and continue this until element -3 is reached with a jump of -1. This continues with each row as they are appended in reverse order with reverse order of column elements

m
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
m[:2]
 [[0 1 2 3]
 [4 5 6 7]]
m[2:5]
 [[ 8  9 10 11]]
b[2,3]
 23
b[-2,-3]
 31
b[0:5,1]
 [ 1 11 21 31 41]
b[:,1]
 [ 1 11 21 31 41]
b[2:5,1]
 [21 31 41]
b[2:5,:]
 [[20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
b[:,::2]
 [[ 0  2]
 [10 12]
 [20 22]
 [30 32]
 [40 42]]
b[-1]
 [40 41 42 43]
b[-1,-1]
 43
b[-2:]
 [[30 31 32 33]
 [40 41 42 43]]
b[-2:0]
 []
b[-2:0:-1]
 [[30 31 32 33]
 [20 21 22 23]
 [10 11 12 13]]
b[-1::-1]
 [[40 41 42 43]
 [30 31 32 33]
 [20 21 22 23]
 [10 11 12 13]
 [ 0  1  2  3]]
b[-1::-1,-1::-1]
 [[43 42 41 40]
 [33 32 31 30]
 [23 22 21 20]
 [13 12 11 10]
 [ 3  2  1  0]]
b[-1:-3:-1, -1:-3:-1]
 [[43 42]
 [33 32]]


In [ ]:
# ------------------------------
#         3D RANGE (3 axes)
# ------------------------------
# syntax: array[2DArrayStartIncluded : 2DArrayEndExcluded : 2DArrayStep, RowStartIncluded: RowEndExcluded: RowStep, ColumnStartIncluded : ColumnEndExcluded : ColumnStep]  

c = np.array([
            [ [1,2,3,4], 
              [5,6,7,8],
              [9,10,11,12]],

            [ [13,14,15,16],
              [17,18,19,20],
              [21,22,23,24]]
            ])

print(f"c.shape\n",c.shape)                  
print(f"c[1]\n",c[1])
print(f"c[1, :, :]\n",c[1, :, :])
print(f"c[1, ...]\n",c[1,...])                                    # in 2nd 2D arrays take all column elements of all rows                 
print(f"c[1, 2]\n",c[1, 2])
print(f"c[1, 2, 3]\n",c[1, 2, 3])
print(f"c[:, :, 2]\n",c[:, :, 2])                                    # in all 2D arrays take 2nd column elements of all rows  
print(f"c[..., 2]\n",c[..., 2])                                    # in all 2D arrays take 2nd column elements of all rows  
print(f"c[1, :, 2]\n",c[1, :, 2])                                    # in 2nd 2D array take only 2nd column elements of all rows
print(f"c[1, 0:2, 3]\n",c[1, 0:2, 3])                                # in 2nd 2D array take only 3rd column elements of two rows 0, 1 

# dealing only 2D arrays 
print(f"c[-1:0:-1]\n",c[-1:0:-1])                                # c[-1: 0: -1] == c[1: 0: -1] start at 2nd 2D array append it into a list then go to next step i.e 1 + (-1) = 0 as 0 is excluded so we only got 3D array contaning last/ 2nd 2D array
print(f"c[-1::-1]\n",c[-1::-1])                                  # c[-1::-1] == c[1::-1] start at 2nd 2D array append it into the list and then go to next step i.e 1 + (-1) = 0 as there is no limit we have to go till end so now append this 1st 2D array into same list. So that we got both 2D arrays in 3D array in reverse order

# dealing 2D arrays and rows
print(f"c[-1::-1, -1::-1]\n",c[-1::-1, -1::-1])      
print(f"c[-1::-1, 0:2]\n",c[-1::-1, 0:2])                          # in each opposite order 2D arrays i want only 0, 1 rows

# dealing 3D arrays and rows and columns
print(f"c[-1::-1, -1::-1, -1::-1]\n",c[-1::-1, -1::-1, -1::-1])  

c.shape
 (2, 3, 4)
c[1]
 [[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
c[1,:,:]
 [[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
c[1,...]
 [[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
c[1,2]
 [21 22 23 24]
c[1,2,3]
 24
c[:,:,2]
 [[ 3  7 11]
 [15 19 23]]
c[...,2]
 [[ 3  7 11]
 [15 19 23]]
c[1,:,2]
 [15 19 23]
c[1,0:2,3]
 [16 20]
c[-1:0:-1]
 [[[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
c[-1::-1]
 [[[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
c[-1::-1,-1::-1]
 [[[21 22 23 24]
  [17 18 19 20]
  [13 14 15 16]]

 [[ 9 10 11 12]
  [ 5  6  7  8]
  [ 1  2  3  4]]]
c[-1::-1,0:2]
 [[[13 14 15 16]
  [17 18 19 20]]

 [[ 1  2  3  4]
  [ 5  6  7  8]]]
c[-1::-1,-1::-1,-1::-1]
 [[[24 23 22 21]
  [20 19 18 17]
  [16 15 14 13]]

 [[12 11 10  9]
  [ 8  7  6  5]
  [ 4  3  2  1]]]


In [13]:
# ============================================================
#                    SHAPE MANIPULATION
# ============================================================
# each method return new array does not modify existing one

a = np.floor(np.random.default_rng(1).random((3,4)) * 10)
print(a)
print(a.ravel())                                                # a.ravel() == a.ravel(order="C"); it read elements in C-style row by row order 
print(a.reshape((6,2)))                                         # a.reshape((6,2)) == a.reshape((6,2), order="C"); it write elements in C-style row by row order; it reads and write in C-style order row by row
print(a.ravel(order="F"))                                       # it read elements Fortan-style column by column order
print(a.reshape((6,2), order="F"))                              # it write elements in Fortan-style column by column order like this column1 = [5, 3, 4, 9, 4, 0] column2 = [1, 8, 7, 9, 4, 5; it reads and write in fortan order column by column
print(a.T)


[[5. 9. 1. 9.]
 [3. 4. 8. 4.]
 [5. 0. 7. 5.]]
[5. 9. 1. 9. 3. 4. 8. 4. 5. 0. 7. 5.]
[[5. 9.]
 [1. 9.]
 [3. 4.]
 [8. 4.]
 [5. 0.]
 [7. 5.]]
[5. 3. 5. 9. 4. 0. 1. 8. 7. 9. 4. 5.]
[[5. 1.]
 [3. 8.]
 [5. 7.]
 [9. 9.]
 [4. 4.]
 [0. 5.]]
[[5. 3. 5.]
 [9. 4. 0.]
 [1. 8. 7.]
 [9. 4. 5.]]


In [85]:
# New Axis 
# np.newaxis simply add a new axis either row or column in the array
# All original dimensions stay the same. Only a new dimension is added with size 1

a = np.array([1, 2, 3])
print(f"a = \n{a}, shape = {a.shape}")

a_row = a[np.newaxis, :]    # (3,) changed to (1, 3) → Added a new "1" in front
print(f"a_row = \n{a_row}, shape = {a_row.shape}\n")

a_col = a[:, np.newaxis]    # (3,) changed to (3, 1) → Added a new "1" after
print(f"a_col = \n{a_col}, shape = {a_col.shape}\n")

a_col_row = a[np.newaxis, np.newaxis]   # (3,) → changed to (1, 3) → changed to (1, 1, 3)
print(f"a_col_row = \n{a_col_row}, shape = {a_col_row.shape}\n")

print(a[np.newaxis, :][:, np.newaxis])
print(a[:, np.newaxis][np.newaxis, :])

a = 
[1 2 3], shape = (3,)
a_row = 
[[1 2 3]], shape = (1, 3)

a_col = 
[[1]
 [2]
 [3]], shape = (3, 1)

a_col_row = 
[[[1 2 3]]], shape = (1, 1, 3)

[[[1 2 3]]]
[[[1]
  [2]
  [3]]]


# Views in Numpy
- A view is a shallow copy of an array. It does not create new data in memory, it just creates another "window" (reference) to the same data.
    - Original array and its view share the same memory buffer
    - Changing one will affect the other
    - It's fast (no data duplication, just metadata like shape and stride is stored separately)

| Operation / Pattern                                   | Produces a **View**? | Notes / Exceptions                                                                  |
| ----------------------------------------------------- | -------------------: | ----------------------------------------------------------------------------------- |
| **Basic slicing** (`a[2:8]`, `a[:, 1:3]`)             |               ✅ View | Slices are views (share memory).                                                    |
| **Fancy indexing** (`a[[1,3]]`, `a[np.array([1,3])]`) |               ❌ Copy | Always makes a copy.                                                                |
| **Boolean indexing** (`a[a>0]`)                       |               ❌ Copy | Returns a new array with matching elements.                                         |
| **`reshape()`**                                       |     ✅ *Usually* view | Returns view if possible (same memory layout/contiguous); otherwise returns a copy. |
| **`transpose()` / `.T`**                              |               ✅ View | Usually view (changes strides). If you then `.copy()` it becomes independent.       |
| **`ravel()`**                                         |   ✅ View if possible | `ravel()` returns view when memory is contiguous; else returns copy.                |
| **`flatten()`**                                       |               ❌ Copy | Always returns a copy.                                                              |
| **`np.concatenate` / `hstack` / `vstack`**            |               ❌ Copy | Needs new contiguous array to store concatenated data.                              |
| **Arithmetic ops (`a+1`, `a*b`)**                     |               ❌ Copy | Produces new array (unless you use out= or in-place operators).                     |
| **In-place ops (`a += 1`)**                           | ✅ In-place (no copy) | Modifies existing array buffer.                                                     |
| **`np.where(condition, x, y)`**                       |               ❌ Copy | Produces new array.                                                                 |
| **`astype(dtype)`**                                   |       ❌ Usually copy | `astype(copy=False)` may avoid copy if same dtype and alignment; otherwise copies.  |
| **`np.copy()` / `.copy()`**                           |               ❌ Copy | Explicit copy.                                                                      |
| **`np.expand_dims`, `np.squeeze`**                    |       ✅ View usually | They adjust shape/strides; sometimes force copy if impossible.                      |
| **structured / record field view (`arr['f']`)**       |               ✅ View | Field access returns a view (but can be tricky with alignment).                     |



In [57]:
x = np.array([1, 2, 3, 4, 5])
y = x[1:4]  # <-- This is a view (slice)
y[:] = 99   # Modify the view
print(x)    # Output: [ 1 99 99 99  5 ]
print(y.base is x)   # True if y is a view of x)
# If y.base is None, then it's a copy, not a view.

[ 1 99 99 99  5]
True


# Broadcasting in Numpy
<img src="./images/image.png" width="400" height="400"/>

**Broadcasting** is NumPy’s way of allowing **operations between arrays of different shapes**, by **automatically expanding** (virtually, without copying memory) smaller arrays along dimensions where needed.
It **pretends** to "stretch" the array so that both operands appear to have the same shape — **but doesn't actually copy** data → super efficient.

When performing operations between two arrays, **NumPy compares shapes from the trailing (rightmost) dimension backwards**:

| Dimension Comparison        | Valid? | What Happens                                                    |
| --------------------------- | ------ | --------------------------------------------------------------- |
| Same size                   | ✅      | Use as-is                                                       |
| One of them is 1            | ✅      | The one with 1 gets **broadcast (repeated virtually)** to match |
| Sizes differ and none are 1 | ❌      | ❌ Error: `ValueError: operands could not be broadcast together` |

In [5]:
# Example 1 — Scalar with Array (Trivial Broadcasting)
# Scalar `10` is broadcasted to `[10, 10, 10]`

a = np.array([1, 2, 3])
b = 10
print(a + b)

# Example 2 - Two vectors (one is broadcasted)
'''
Let's say we are doing `A (3,4) + B (1,4) = shape(4,)`:
| Step                             | A Shape           | B Shape   
| -------------------------------  | ---------------   | --------- 
| Compare last dim → 4 & 4         | same              | keep      
| Compare 2nd last dim → 3 & 1     | (1 expands to 3)  | broadcast 
Final Broadcast Shape → (3,4)  

a = [[0,1,2,3]
     [4,5,6,7]
     [8,9,10,11]]  ( No need to broadcasting )

b = [[0,1,2,3]]
broadcasted to 
b = [[0,1,2,3]
     [0,1,2,3]
     [0,1,2,3]]
'''

a = np.arange(0, 12).reshape(3, 4)
b = np.arange(0, 4).reshape(1, 4)
print(a + b)

# Example 3 — Two vectors (both are broadcasted)
'''
| Array | Shape  | Broadcast To |
| ----- | ------ | ------------ |
| `a`   | (1, 3) | (3, 3)       |
| `b`   | (3, 1) | (3, 3)       |

a is broadcast to [[1,2,3]
                   [1,2,3]
                   [1,2,3]]
b is broadcast to [[10,10,10]
                    [20,20,20]
                    [30,30,30]]
'''

a = np.array([[1, 2, 3]])          # shape → (1, 3)
b = np.array([[10], 
              [20], 
              [30]])               # shape → (3, 1)
c = a + b
print(c)

# Example 4 - Error
# Reason → comparing second dimension: 3 & 2 → Cannot broadcast (none is 1)

a = np.ones((4,4))
b = np.ones((2,4))
# print(a + b)

# Example 5 - Same Cases
b = np.array([[100]])
X = np.array([[200], [300]])
print(X + b)

b = np.array([100])
X = np.array([[200], [300]])
print(X + b)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.dot(a, b))   # 1*4 + 2*5 + 3*6 = 32
print(a @ b)          # same = 32

[11 12 13]
[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]
[[11 12 13]
 [21 22 23]
 [31 32 33]]
[[300]
 [400]]
[[300]
 [400]]
32
32


# Fancy Indexing

Fancy indexing in NumPy allows you to access elements of an array using integer arrays or lists of indices, instead of just slices.  
It provides a flexible way to select arbitrary elements from 1D, 2D, or higher-dimensional arrays.  
Unlike basic slicing, fancy indexing always creates a copy of the data rather than a view.

In [ ]:
# ============================================================
#                    1D Array
# ============================================================
# syntax: array[[a,b,c,...]] where a,b,c,.. are indexs of column elements to be selected. They can be random like [1,2,5,8,6] not following any jumping order  

d = np.arange(10, 20)
print(f"d\n", d)

print(f"d[[1,2,3]]\n",d[[1,2,3]])
print(f"d[[0,-1]]\n",d[[0,-1]])
print(f"d[[1,1,2]]\n",d[[1,1,2]])
d[[1,3]] = [21,23]
print(f"d[[1,3]] = [21,23]\n",d)
d[[2,2]] = [20,22]                                          # duplicate assignment last write wins
print(f"d[[2,2]] = [20,22]\n",d)

d
 [10 11 12 13 14 15 16 17 18 19]
d[[1,2,3]]
 [11 12 13]
d[[0,-1]]
 [10 19]
d[[1,1,2]]
 [11 11 12]
d[[1,3]] = [21,23]
 [10 21 12 23 14 15 16 17 18 19]
d[[2,2]] = [20,22]
 [10 21 22 23 14 15 16 17 18 19]


In [ ]:
# ============================================================
#                    2D Array
# ============================================================

# This syntax is such that before making the resultant 2D array we are applying the row and column filters on the original array
#
# syntax: this is pairing (elementwise selection) not grid selection as both sides are arrays of the same shape
#         array[[a,b,c,...], [d,e,f,...]]
#
# syntax: this is grid/ block selection in which we does not pass array on both sides so NumPy forms a grid/block of all combinations.
#         array[[a,b,c,...], ColumnStartIncluded : ColumnEndExcluded : ColumnStep] or
#         array[RowStartIncluded: RowEndExcluded: RowStep, [d,e,f,...]] or
#         array[RowStartIncluded: RowEndExcluded: RowStep, ColumnStartIncluded : ColumnEndExcluded : ColumnStep]
# 
# syntax: this is Chained indexing (indexing the result again) such that we first make the resultant 2D array following above mentioned indexing and after that on the resultant 2D array we apply the filter using above mentioned inddexing.
#         array[[a,b,c,...], [d,e,f,...]][[a,b,c,...], [d,e,f,...]] or
#         array[[a,b,c,...]][[d,e,f,...]] (In this case we are filtering out rows first from original array and then from the resultant 2D array. So in resultant we are just filtering out rows from original array)
#         array[:,[a,b,c,...]][:,[d,e,f,...]] (In this case we are filtering out columns first from original array and then from the resultant 2D array. So in resultant we are just filtering out columns from original array)

e =  np.array(
    [[0, 1, 2, 3],
     [4, 5, 6, 7],
     [8, 9, 10, 11]]
    )

# GRID SELECTION
print(f"e[[0,2]]\n",e[[0,2]])                               # Get two rows at index 0, 2 and then append into resultant 2D array.
print(f"e[[0,2]][1]\n",e[[0,2]][1])                         # Get two rows at index 0, 2 and then append into resultant 2D array. After that filter out resultant 2D array by apply indexing on it to return single 1D array
print()

print(f"e[[2]]\n",e[[2]])                                   # Take third row append that into resultant 2D array ("e[[2]]") 
print(f"e[[2],:]\n",e[[2],:])                               # Take third row, but before appending, take all of the elements of that row, and then append that into resultant 2D array
print(f"e[[2]][:]\n",e[[2]][:])                             # Take third row append that into resultant 2D array ("e[[2]]"). After that filter out and take all rows of resultant 2D array
print(f"e[[2]][:,:]\n",e[[2]][:,:])                         # Take third row append that into resultant 2D array ("e[[2]]"). After that filter out and take all rows and all columns of resultant 2D array
print()

print(f"e[[0,2],1]\n",e[[0,2],1])                           # Get two rows at index 0, 2 of original array then apply column filtering on them by selecting only the first column. After that append these rows in the 2D resultant array
print(f"e[[0,2]][:, 1]\n",e[[0,2]][:, 1])                   # Get two rows at index 0, 2 and then append into resultant 2D array. After that filter out the resultant 2D array so to get only 2nd elements of all rows in it
print(f"e[[0,2]][0, 1]\n",e[[0,2]][0, 1]) 
print()

print(f"e[:,[0,3]]\n",e[:,[0,3]])                           # Get all rows from the original array after that filter out columns and take 0th and 3rd elements of all rows. Append these rows in the resultant 2D array
print(f"e[[0,2]][:,[1,3]]\n",e[[0,2]][:,[1,3]])

# PAIRWISE SELECTION
print(f"e[[0,2],[1,3]]\n",e[[0,2],[1,3]])                   # selects (0,1) and (2,3)
try:
    print(f"e[[0,2],[1,2,3]]\n",e[[0,2],[1,2,3]])           
except Exception as err:
    print("Error:", err)


e[[0,2]]
 [[ 0  1  2  3]
 [ 8  9 10 11]]
e[[0,2]][1]
 [ 8  9 10 11]

e[[2]]
 [[ 8  9 10 11]]
e[[2],:]
 [[ 8  9 10 11]]
e[[2]][:]
 [[ 8  9 10 11]]
e[[2]][:,:]
 [[ 8  9 10 11]]

e[[0,2],1]
 [1 9]
e[[0,2]][:, 1]
 [1 9]
e[[0,2]][0, 1]
 1

e[:,[0,3]]
 [[ 0  3]
 [ 4  7]
 [ 8 11]]
e[[0,2]][:,[1,3]]
 [[ 1  3]
 [ 9 11]]
e[[0,2],[1,3]]
 [ 1 11]
Error: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 


In [ ]:
# Fancy indexing vs slicing: copy vs view (important gotcha)
# Slicing returns a view; fancy indexing returns a copy.

e = np.arange(12).reshape(3,4)

# slicing -> view
s = e[:2]       # view of first 2 rows
s[0,0] = 999
# e is now changed at [0,0] -> 999
print(s)
print(e)

# fancy indexing -> copy
e = np.arange(12).reshape(3,4)   # fresh e
f = e[[0,1]]     # fancy indexing → copy
f[0,0] = 555
# e remains unchanged
print(e)
print(f)


#Assignment to original using fancy indices
e = np.arange(12).reshape(3,4)
e[[0,2],[1,3]] = -1
print(e)

[[999   1   2   3]
 [  4   5   6   7]]
[[999   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[555   1   2   3]
 [  4   5   6   7]]
[[ 0 -1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 -1]]


In [ ]:
# Assignment to original using fancy indices

e = np.arange(12).reshape(3,4)
e[[0,2],[1,3]] = -1
print(f"e:\n{e}")

# When using arrays of indices, the shape of the result reflects the shape of the index arrays rather than the shape of the array being indexed
rng = np.random.default_rng(seed=1701)
print(f"x:\n{x}")
x = rng.integers(100, size=10)
ind = np.array([[3,7], [4,5]])
print(f"ind:\n", ind)
print(f"x[ind]:\n",x[ind])

#  The pairing of indices in fancy indexing follows all the broadcasting rules. So, for example, if we combine a column vec‐tor and a row vector within the indices, we get a two-dimensional result
y = np.arange(12).reshape(3,4)
print(f"y:\n{y}")
print(f"y[[0,1,2], [2,1,3]]:\n {y[[0,1,2], [2,1,3]]}")

row = np.array([0,1,2])
print(f"y[row[:, np.newaxis], [2,1,3]]:\n {y[row[:, np.newaxis], [2,1,3]]}")
'''
Here broadcasting will be like this
row = [0,1,2]   -> (3,)
row = row[: newaxis]    -> (3,1)
row =  [[0],
        [1],
        [2]]
col = [2,1,3]
row_broadcasted = [[0,0,0],
                   [1,1,1],
                   [2,2,2]]
col_broadcasted = [[2,1,3],
                   [2,1,3],
                   [2,1,3]]

pairs of indices = element in result = 
                [[(0,2) (0,1) (0,3)],
                 [(1,2) (1,1) (1,3)],
                 [(2,2) (2,1) (2,3)]]
'''

# Combining fancy indexing with masking


e:
[[ 0 -1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 -1]]
x:
[90 40  9 30 80 67 39 15 33 79]
ind:
 [[3 7]
 [4 5]]
x[ind]:
 [[30 15]
 [80 67]]
y:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
y[[0,1,2], [2,1,3]]:
 [ 2  5 11]
y[[0,1,2][:, np.newaxis], [2,1,3]]:
 [[ 2  1  3]
 [ 6  5  7]
 [10  9 11]]


# Boolean Indexing

In [ ]:
# Boolean Indexing

a = np.arange(5)
mask = [True, False, False, True, True]
print(a[mask])

mask = a % 2 == 0
print(mask)
print(a[mask])

# Creating mask
# In Numpy creating mask using comparison returns numpy.ndarray() with dtype = bool
a = np.arange(50)
print(a > 25)

# Using mask
print(a[a > 25])

[0 3 4]
[ True False  True False  True]
[0 2 4]
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True]
[26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [19]:
# Making Complex 2-D ndarray with schema/ conditions on dtypes of columns

''' 
np.zeros((2,), ...) → makes an array of 2 elements, initialized to zero.

dtype=[("A", "i4"), ("B", "f4"), ("C", "a10")] → defines a structured dtype:
"A" → field name, type: i4 = 4-byte int (int32)
"B" → field name, type: f4 = 4-byte float (float32)
"C" → field name, type: S10 = string of length 10 
'''
# ===============================
# 1. DEFINE A STRUCTURED DTYPE
# ===============================

dtype = np.dtype([
    ("A", "i4"),    # 4-byte integer
    ("B", "f4"),    # 4-byte float
    ("C", "S10")    # 10-character fixed-width ASCII string
])

print("Structured dtype:")
print(dtype)
print("Field names:", dtype.names)
print("Field definitions:", dtype.fields)
print()

# ===============================
# 2. CREATE STRUCTURED ARRAYS
# ===============================

# Method 1: zeros
data = np.zeros((2,), dtype=dtype)
print("Empty structured array (zeros):")
print(data)
print()

# Fill values with assignment
data[:] = [(1, 2.0, "Hello"), (2, 3.0, "World")]
print("After filling with tuples:")
print(data)
print()

# Method 2: directly from list-of-tuples
data2 = np.array(
    [(10, 20.5, "Alpha"), (30, 40.5, "Beta")],
    dtype=dtype
)
print("Direct creation from tuples:")
print(data2)
print()
# ===============================
# 3. FIELD ACCESS
# ===============================
print("Column access:")
print("A:", data['A'])   # int array
print("B:", data['B'])   # float array
print("C:", data['C'])   # byte string array
print()

print("Row access:")
print("Row 0:", data[0])          # one record (np.void)
print("Row 0, field 'B':", data[0]['B'])
print()

# ===============================
# 4. FIELD ASSIGNMENT
# ===============================
print("Assigning new values...")
data['A'] = [100, 200]       # assign whole column
data[1] = (300, 3.14, "Hi")  # assign one record
print(data)
print()

# ===============================
# 5. BOOLEAN MASKING
# ===============================
mask = data['A'] > 150
print("Mask (A > 150):", mask)
print("Filtered rows:")
print(data[mask])
print()


Structured dtype:
[('A', '<i4'), ('B', '<f4'), ('C', 'S10')]
Field names: ('A', 'B', 'C')
Field definitions: {'A': (dtype('int32'), 0), 'B': (dtype('float32'), 4), 'C': (dtype('S10'), 8)}

Empty structured array (zeros):
[(0, 0., b'') (0, 0., b'')]

After filling with tuples:
[(1, 2., b'Hello') (2, 3., b'World')]

Direct creation from tuples:
[(10, 20.5, b'Alpha') (30, 40.5, b'Beta')]

Column access:
A: [1 2]
B: [2. 3.]
C: [b'Hello' b'World']

Row access:
Row 0: (1, 2.0, b'Hello')
Row 0, field 'B': 2.0

Assigning new values...
[(100, 2.  , b'Hello') (300, 3.14, b'Hi')]

Mask (A > 150): [False  True]
Filtered rows:
[(300, 3.14, b'Hi')]



# Exploring NumPy’s Ufuncs
- Ufuncs exist in two flavors: unary ufuncs, which operate on a single input, and binary
ufuncs, which operate on two inputs.

### Unary Ufuncs

In [62]:
x = np.arange(4)

# Arithematic Operations
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # floor division
print("-x = ", -x) # negation  
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)
print("-(0.5*x + 1) ** 2 = ", -(0.5*x + 1) ** 2) # order of operation is respected

# Absolute Operation
y = np.array([-2, -1, 0, 1, 2])
print("abs(y) = ", abs(y))
print("abs(y) = ", np.absolute(y))

# Trigonometric Operations
theta = np.linspace(0, np.pi, 3)
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))
theta = [-1, 0, 1]
print("arcsin(x) = ", np.arcsin(theta))
print("arccos(x) = ", np.arccos(theta))
print("arctan(x) = ", np.arctan(theta))

# Exponents and Logarithms
x = [1,2,3]
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3., x))
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

# Aggregations
x = [1,2,3,4]
print("np.add.reduce(x) =", np.add.reduce(x))
print("np.add.accumulate(x) =", np.add.accumulate(x))
print("np.multiply.reduce(x) =", np.multiply.reduce(x))
print("np.multiply.accumulate(x) =", np.multiply.accumulate(x))

# Outer Products
print(np.multiply.outer(x, x))

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]
-(0.5*x + 1) ** 2 =  [-1.   -2.25 -4.   -6.25]
abs(y) =  [2 1 0 1 2]
abs(y) =  [2 1 0 1 2]
theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3.  9. 27.]
ln(x) = [0.         0.69314718 1.09861229]
log2(x) = [0.        1.        1.5849625]
log10(x) = [0.         0.30103    0.47712125]
np.add.reduce(x) = 10
np.add.accumulate(x) = [ 1  3  6 10]
np.multiply.reduce(x) = 24
np.multiply.accumulate(x) = [ 1  2  6 24]
[[ 1  2  3  4]
 [ 2

### Specifying Output
- For large calculations, it is sometimes useful to be able to specify the array where the
result of the calculation will be stored. For all ufuncs, this can be done using the out
argument of the function

In [55]:
# Case-1: Storing Result in simple order in resultant array (y)
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

# Case-2: Storing result with steps of 2 (using views)
''' 
If we had instead written y[::2] = 2 ** x, this would have resulted in the creation
of a temporary array to hold the results of 2 ** x, followed by a second operation
copying those values into the y array. This doesn't make much of a difference for such
a small computation, but for very large arrays the memory savings from careful use of
the out argument can be significant.
'''
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 0. 10. 20. 30. 40.]
[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [4]:
rng = np.random.default_rng(1345)
X = rng.random((4, 2))
print(X)                    # shape (4, 2)
print(X[:, np.newaxis])     # shape (4, 1, 2) -> Inserted a new axis after the row index
print(X[np.newaxis, :])     # shape (1, 4, 2) -> Inserted a new axis before row index

[[0.83460297 0.7691589 ]
 [0.46190998 0.62125838]
 [0.68087454 0.68851548]
 [0.51451087 0.29515641]]
[[[0.83460297 0.7691589 ]]

 [[0.46190998 0.62125838]]

 [[0.68087454 0.68851548]]

 [[0.51451087 0.29515641]]]
[[[0.83460297 0.7691589 ]
  [0.46190998 0.62125838]
  [0.68087454 0.68851548]
  [0.51451087 0.29515641]]]


In [2]:
print(np.squeeze(1))
print(np.squeeze([1]))
print(np.squeeze([[1]]))
print(np.squeeze([[[1]]]))
print(np.squeeze([[[1], [2]], [[1], [2]]]))

1
1
1
1
[[1 2]
 [1 2]]


# Clip Method Avoids Pitfalls

In [7]:
y_true = np.array([1, 0, 1, 0])
y_pred = np.array([1, 1, 0, 1])
# print(y_true * np.log(y_pred))
# print((1 - y_true) * np.log(1 - y_pred))
# print(np.sum(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred)))

# To avoid this is use clip method
eps = 1e-15
y_pred = np.clip(y_pred, eps, 1 - eps)
'''
limit predictions to this range
1e-15 ≤ y_pred ≤ 1-(1e-15)
0.000000000000001 ≤ y_pred ≤ 1-0.000000000000001
0.000000000000001 ≤ y_pred ≤ 0.999999999999999
y_pred = [1,1,0,1]
becomes
[0.999999999999999,
 0.999999999999999,
 0.000000000000001,
 0.999999999999999]
'''

print(y_pred)
print(y_true * np.log(y_pred))
print((1 - y_true) * np.log(1 - y_pred))
print(np.sum(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred)))

# It also works in other cases as
arr = [5, -2, 7, 3]
np.clip(arr, 0, 6)
print(arr)

[1.e+00 1.e+00 1.e-15 1.e+00]
[-9.99200722e-16 -0.00000000e+00 -3.45387764e+01 -0.00000000e+00]
[ -0.         -34.53957599  -0.         -34.53957599]
-103.61792837959243
[5, -2, 7, 3]


# Random Functions in Numpy

In [ ]:
np.random.seed(42)

# np.random.rand() generates random floats between: 0 <= x < 1 from uniform distribution

# Single Number
print(np.random.rand())

# 1-D Array
print(np.random.rand(5))

# 2-D Array
print(np.random.rand(2,3))

0.3745401188473625
[0.95071431 0.73199394 0.59865848 0.15601864 0.15599452]
[[0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]]


In [6]:
# np.random.randn() generates random floats between: 0 <= x < 1 from normal distribution
# Instead of uniform probability: middle values appear more, extreme values appear less

print(np.random.randn())
print(np.random.randn(3,4))

-0.22577630048653566
[[ 0.0675282  -1.42474819 -0.54438272  0.11092259]
 [-1.15099358  0.37569802 -0.60063869 -0.29169375]
 [-0.60170661  1.85227818 -0.01349722 -1.05771093]]


In [12]:
# np.random.randint(): Random integers
# Format: x = np.random.randint(low, high, size) ; where low <= x < high

# Single Number
print(np.random.randint(1,10))

# 1-D Array
print(np.random.randint(1,10, size=5))

# 2-D Array
print(np.random.randint(1, 10, size=(2, 3)))

1
[5 5 7 8 4]
[[4 1 6]
 [2 2 2]]


In [9]:
# np.random.random() Very similar to rand().
# rand(2,3)	separate dimensions
# random((2,3))	tuple

np.random.random((2,3))

array([[0.42515587, 0.20794166, 0.56770033],
       [0.03131329, 0.84228477, 0.44975413]])

In [8]:
arr = [10,20,30,40]

# Single Selection
print(np.random.choice(arr))

# Multiply Selections with Replacement (Duplicates can occur)
print(np.random.choice(arr, size=3, replace=True)) # By default replace is True

# Multiply Selections Without Replacement (Duplicates cannot occur)
print(np.random.choice(arr, size=3, replace=False))

# Weighted Probability (Defining Underlining Distribution or likelihood of data points)
print(np.random.choice(
    [0,1], # Only 2 values 
    size=10, # 1-D array of size = 10 
    p=[0.8,0.2] # 80% values will be 0 and other 20% values will be 1 
))

# It also works on single number 
print(np.random.choice(5))  # same as np.random.choice(np.arange(5))

40
[30 30 30]
[30 10 40]
[1 0 0 0 1 1 0 0 1 0]
4


In [45]:
# np.random.shuffle(); Shuffles ORIGINAL array.

arr = np.array([1,2,3,4])
np.random.shuffle(arr)
print(arr)

[1 2 4 3]


In [75]:
# np.random.permutation(); Returns shuffled COPY.

new_arr = np.random.permutation(arr)
print(arr)
print(new_arr)

[1 2 4 3]
[1 2 4 3]


In [ ]:
# np.random.uniform(low, high, size); low <= x < how; Custom uniform range.

# 5 <= x < 10
print(np.random.uniform(5,10))
print(np.random.uniform(5,10,(2,3)))

9.910841716647177
[[7.58317946 6.30414587 9.9812685 ]
 [9.82709676 7.79146727 9.41318172]]


In [79]:
# np.random.normal(); Normal distribution.
# format: np.random.normal(mean, std, size)

print(np.random.normal(0,1,5))
print(np.random.normal(100,15,10))

[-0.60139725 -0.84661436  0.81615272  0.47170729 -0.2854893 ]
[115.97938703 112.8099668  126.82890786 108.50341106  97.53249349
  97.85513598  70.98144707 102.25988565  99.7642759   80.04888902]


# Counting Occurances

In [10]:
# np.unique(..., return_counts=True)
arr = np.array([1, 2, 2, 2, 3, 3, 4])

values, counts = np.unique(arr, return_counts=True)
print(values)
print(counts)

# Printing in dictionary form
print(dict(zip(map(int, values), map(int, counts))))

[1 2 3 4]
[1 3 2 1]
{1: 1, 2: 3, 3: 2, 4: 1}


In [25]:
# np.bincount(): Much faster because it uses the integer itself as an index.

arr = np.array([0,1,1,3,3,3,10])
counts = np.bincount(arr)

print(counts)

[1 2 0 3 0 0 0 0 0 0 1]


In [14]:
# Counting specific value

arr = np.array([1,2,2,2,4])
print(np.sum(arr == 2))

3


In [23]:
# Counting Unique Rows
matrix = np.array([
    [1,2],
    [3,4],
    [1,2]
])

print(np.unique(matrix, axis=0))

values, counts = np.unique(matrix, axis=0, return_counts=True)
print(dict(zip(map(tuple, values), map(int, counts))))

[[1 2]
 [3 4]]
{(np.int64(1), np.int64(2)): 2, (np.int64(3), np.int64(4)): 1}
